import { createApp, ref, computed, onMounted } from 'vue'
import './style.css'
const API = import.meta.env.VITE_API_URL || 'http://localhost:3000'
const token = ref(localStorage.getItem('admin_token') || ''); const view = ref('dashboard'); const loading = ref(false); const error = ref(''); const dashboard = ref(null); const users = ref([]); const trips = ref([]); const username = ref(''); const password = ref('')
async function api(path, options = {}) { const res = await fetch(`${API}${path}`, { ...options, headers: { 'Content-Type': 'application/json', ...(token.value ? { Authorization: `Bearer ${token.value}` } : {}), ...(options.headers || {}) } }); if (!res.ok) throw new Error((await res.json().catch(() => ({}))).message || 'Request failed'); return res.json() }
async function load() { loading.value = true; error.value = ''; try { if (view.value === 'dashboard') dashboard.value = await api('/admin/dashboard'); if (view.value === 'users') users.value = (await api('/admin/users')).data; if (view.value === 'trips') trips.value = (await api('/admin/trips')).data } catch (e) { error.value = e.message; if (e.message.includes('session')) { token.value = ''; localStorage.removeItem('admin_token') } } finally { loading.value = false } }
async function apiLogin() { try { error.value = ''; const result = await api('/admin/auth/login', { method: 'POST', body: JSON.stringify({ username: username.value, password: password.value }) }); token.value = result.token; localStorage.setItem('admin_token', token.value); load() } catch (e) { error.value = e.message } }
function logout() { token.value = ''; localStorage.removeItem('admin_token'); view.value = 'dashboard' }
const title = computed(() => ({ dashboard: 'Dashboard', users: 'Users', trips: 'Trips' }[view.value]))
const App = { setup() { onMounted(() => token.value && load()); return { token, view, title, dashboard, users, trips, loading, error, username, password, apiLogin, logout, load } }, template: `<div v-if="!token" class="login"><form @submit.prevent="apiLogin"><div class="brand">✦ Cross-border Admin</div><h1>Welcome back</h1><p>Sign in to manage riders and trips.</p><input v-model="username" placeholder="Admin username" autocomplete="username" required/><input v-model="password" type="password" placeholder="Password" autocomplete="current-password" required/><button>Sign in</button><small v-if="error">{{error}}</small></form></div><div v-else class="shell"><aside><div class="brand">✦ Cross-border</div><nav><button :class="{active:view==='dashboard'}" @click="view='dashboard';load()">▦ Dashboard</button><button :class="{active:view==='users'}" @click="view='users';load()">♙ Users</button><button :class="{active:view==='trips'}" @click="view='trips';load()">⇄ Trips</button></nav><button class="logout" @click="logout">Sign out</button></aside><main><header><div><span class="eyebrow">ADMIN CONSOLE</span><h1>{{title}}</h1></div><button class="refresh" @click="load">↻ Refresh</button></header><div v-if="error" class="error">{{error}}</div><section v-if="view==='dashboard' && dashboard" class="cards"><article><span>Total users</span><strong>{{dashboard.users}}</strong></article><article><span>Total trips</span><strong>{{dashboard.trips}}</strong></article><article><span>Pending trips</span><strong>{{dashboard.pendingTrips}}</strong></article><article><span>Completed trips</span><strong>{{dashboard.completedTrips}}</strong></article></section><section v-if="view==='users'" class="panel"><table><thead><tr><th>Name</th><th>Phone</th><th>Joined</th><th>ID</th></tr></thead><tbody><tr v-for="u in users" :key="u.id"><td>{{u.name || '—'}}</td><td>{{u.phone || '—'}}</td><td>{{new Date(u.createdAt).toLocaleDateString()}}</td><td class="muted">{{u.id}}</td></tr></tbody></table></section><section v-if="view==='trips'" class="panel"><table><thead><tr><th>Route</th><th>Region</th><th>Scheduled</th><th>Status</th></tr></thead><tbody><tr v-for="t in trips" :key="t.id"><td><b>{{t.origin}}</b><br/><span class="muted">→ {{t.destination}}</span></td><td>{{t.region}}</td><td>{{new Date(t.scheduledAt).toLocaleString()}}</td><td><span class="status" :class="t.status.toLowerCase()">{{t.status}}</span></td></tr></tbody></table></section><div v-if="loading" class="loading">Loading…</div></main></div>` }
createApp(App).mount('#app')
