<template>
  <view class="address-page">
    <view class="address-header">
      <image class="back" src="/static/messages/back.svg" mode="aspectFit" @tap="$emit('close')" />
      <text class="title">地址選擇</text>
      <view class="city-search"><text class="city">{{ currentCity }}</text><image class="city-location" src="/static/home/address/city-location.svg" mode="aspectFit" @tap="$emit('locate')" /><view class="search-box"><image class="search-icon" src="/static/home/address/search.svg" mode="aspectFit" /><input v-model="keyword" class="search-input" placeholder="" confirm-type="search" /></view><text class="search-action">搜索</text></view>
    </view>
    <view class="current-card"><text class="current-title">當前定位城市：{{ currentCity }}</text><view class="current-place" @tap="$emit('use-current')"><image src="/static/home/route/origin.svg" mode="aspectFit" /><view><text class="place-name">{{ currentLocationLabel }}</text><text class="place-address">{{ detailedAddress }}</text></view></view></view>
    <view class="recommend-list"><view class="recommend-title"><image src="/static/home/route/destination.svg" mode="aspectFit" /><text>推薦地點</text></view><view v-for="place in filteredPlaces" :key="place.name" class="place-row" @tap="$emit('select', place.name)"><image src="/static/home/route/destination.svg" mode="aspectFit" /><view><text class="place-name">{{ place.name }}</text><text class="place-address">{{ place.address }}</text></view></view></view>
  </view>
</template>
<script setup lang="ts">
import { computed, ref } from 'vue'
const props = defineProps<{ selecting: 'origin' | 'destination'; locationLabel: string; detailedAddress: string }>()
defineEmits<{ close: []; select: [value: string]; locate: []; 'use-current': [] }>()
const keyword = ref('')
const currentLocationLabel = computed(() => props.locationLabel || '目前位置')
const currentCity = computed(() => currentLocationLabel.value.split(' · ')[0] || '目前城市')
const places = computed(() => props.selecting === 'origin' ? [{ name: '香港國際機場', address: '香港特別行政區-離島區-香港赤臘角天路1號' }, { name: '香港海洋公園', address: '香港特別行政區-南區-香港香港仔黃竹坑180號' }, { name: '香港迪士尼樂園', address: '香港特別行政區-荃灣區-大嶼山竹篙灣' }, { name: '香港銅鑼灣時代廣場', address: '香港特別行政區-灣仔區-香港銅鑼灣勿地臣街1號' }, { name: '尖沙咀海港城', address: '香港特別行政區-九龍-尖沙咀廣東道' }, { name: '香港會展中心', address: '香港特別行政區-灣仔區-博覽道1號' }, { name: '亞洲國際博覽館', address: '香港特別行政區-離島區-航展道1號' }, { name: '蘭桂坊', address: '香港特別行政區-中西區-德己立街' }] : [{ name: '深圳灣口岸', address: '廣東省深圳市南山區東濱路1號' }, { name: '深圳寶安國際機場', address: '廣東省深圳市寶安區航城街道' }, { name: '廣州南站', address: '廣東省廣州市番禺區石壁街道' }, { name: '珠海拱北口岸', address: '廣東省珠海市香洲區昌盛路' }])
const filteredPlaces = computed(() => places.value.filter(place => !keyword.value || `${place.name}${place.address}`.includes(keyword.value)))
</script>
<style scoped>
.address-page{position:fixed;top:0;left:0;width:430px;height:932px;z-index:50;background:#f0f2f5;color:#38434a;font-family:'Noto Sans TC',sans-serif;overflow:hidden}.address-header{position:absolute;top:0;left:0;width:430px;height:155px;border-radius:25px;background:#fff}.back{position:absolute;top:60px;left:46px;width:12px;height:25px}.title{position:absolute;top:58px;left:calc(50% - 36px);font-size:18px;font-weight:500}.city-search{position:absolute;top:110px;left:21px;width:388px;height:35px}.city{position:absolute;left:0;top:7px;font-size:14px;white-space:nowrap}.city-location{position:absolute;left:38px;top:7px;width:20px;height:20px}.search-box{position:absolute;left:63px;top:0;width:287px;height:35px;border-radius:20px;background:#f0f2f5}.search-icon{position:absolute;left:11px;top:7px;width:20px;height:20px}.search-input{width:100%;height:35px;padding:0 10px 0 38px;border:0;border-radius:20px;background:transparent;color:#38434a;font-size:14px;box-sizing:border-box}.search-action{position:absolute;left:360px;top:7px;color:#38434a;font-size:14px;white-space:nowrap}.current-card{position:absolute;top:165px;left:5px;width:420px;height:93px;padding:14px 15px;box-sizing:border-box;border-radius:10px;background:#fff}.current-title{display:block;font-size:16px}.current-place{display:flex;align-items:center;margin-top:10px}.current-place image{width:8px;height:15px;margin-right:8px}.place-name,.place-address{display:block}.place-name{font-size:14px;font-weight:700}.place-address{font-size:12px;font-weight:350;white-space:nowrap}.recommend-list{position:absolute;top:278px;left:5px;width:420px;height:540px;overflow-y:auto}.recommend-title{height:60px;border-radius:10px;background:#285cfc;color:#fff;display:flex;align-items:center;padding-left:20px;box-sizing:border-box;font-size:18px;font-weight:500}.recommend-title image{width:15px;height:22px;margin-right:10px}.place-row{height:57px;margin-top:5px;border-radius:10px;background:#fff;display:flex;align-items:flex-start;padding:10px 15px;box-sizing:border-box}.place-row image{width:10px;height:15px;margin:5px 6px 0 0;flex:none}.place-row .place-address{overflow:hidden;text-overflow:ellipsis;max-width:370px}
</style>
