<template>
  <view class="page" :style="responsiveStyle">
    <view class="header"><image class="back" src="/static/wallet/back.svg" mode="aspectFit" @tap="goBack" /><text class="title">退款</text></view>
    <image class="refund-icon" src="/static/refund-status.svg" mode="aspectFit" />
    <text class="refund-title">退款 - 跨境出行 取消訂單</text>
    <view class="amount"><text class="rmb">RMB </text><text class="yen">¥</text><text class="number">101.00</text></view>
    <view class="status"><view class="status-dot">✓</view><text>審核中</text></view>
    <view class="details"><text class="section-title">退款方式</text><text class="method">我的錢包 餘額</text><view class="steps"><view class="step"><view class="circle">1</view><view class="step-copy"><text>退款申請已被接納</text><text class="step-time">01/01/2024 12:00:00</text></view></view><image class="step-line line-one" src="/static/refund-step-line.svg" mode="scaleToFill"/><view class="step"><view class="circle">2</view><view class="step-copy"><text>審核中</text><text class="expected">預計到帳時間：01/01/2024 12:00:00</text></view></view><image class="step-line line-two" src="/static/refund-step-line.svg" mode="scaleToFill"/><view class="step pending"><view class="circle">3</view><text>已退款至餘額</text></view></view><view class="order-link"><text class="order-label">相關訂單紀錄</text><image src="/static/refund-order-arrow.svg" mode="aspectFit"/></view><text class="arrival-label">退款到帳時間</text><text class="arrival-value">01/01/2024</text></view>
  </view>
</template>
<script setup lang="ts">
import { useResponsiveCanvas } from '../../composables/useResponsiveCanvas'
import { closeCachedPage } from '../../utils/navigation'
const { responsiveStyle } = useResponsiveCanvas()
const goBack = () => closeCachedPage('/pages/transactions/transactions')
</script>
<style scoped>
:global(html),:global(body),:global(#app){width:100%;height:100%;margin:0;overflow:hidden}.page{position:fixed;top:0;left:0;width:430px;height:932px;overflow:hidden;background:#F0F2F5;color:#38434A;font-family:'Noto Sans TC',sans-serif}.header{position:absolute;top:0;left:0;width:430px;height:110px;border-radius:25px;background:#fff}.back{position:absolute;top:52px;left:27px;width:24px;height:30px}.title{position:absolute;top:58px;left:50%;transform:translateX(-50%);font-size:18px;font-weight:500}.refund-icon{position:absolute;top:160px;left:165px;width:100px;height:100px}.refund-title{position:absolute;top:270px;left:calc(50% - 100px);font-size:18px;white-space:nowrap}.amount{position:absolute;top:306px;left:136px;height:43px}.rmb{font-size:14px;font-weight:500}.yen{font-size:26px}.number{margin-left:8px;font-size:30px;font-weight:700}.status{position:absolute;top:359px;left:187px;display:flex;align-items:center;gap:5px;font-size:12px}.status-dot,.circle{width:15px;height:15px;border-radius:50%;background:#285CFC;color:white;font-size:11px;line-height:15px;text-align:center}.details{position:absolute;top:406px;left:15px;width:400px;height:288px;border-radius:10px;background:#fff}.section-title{position:absolute;top:20px;left:20px;font-size:16px}.method{position:absolute;top:22px;right:20px;font-size:14px}.steps{position:absolute;top:63px;left:42px}.step{height:50px;display:flex;align-items:flex-start;gap:10px;color:#285CFC;font-size:12px}.circle{width:20px;height:20px;line-height:20px;flex:none}.pending{color:#38434A}.pending .circle{background:#38434A}.step-copy{display:flex;flex-direction:column;gap:6px}.step-time,.expected{display:block;color:#38434A;font-size:10px}.expected{position:absolute;top:80px;left:30px;width:240px}.step-line{position:absolute;left:0;width:20px;height:2px;transform:rotate(90deg);transform-origin:center}.line-one{top:35px}.line-two{top:85px}.order-link{position:absolute;top:215px;left:20px;width:360px;height:20px}.order-label{position:absolute;top:0;left:0;font-size:14px}.order-link image{position:absolute;top:2px;right:0;width:9px;height:15px}.arrival-label{position:absolute;top:248px;left:20px;font-size:14px}.arrival-value{position:absolute;top:248px;right:20px;font-size:14px}@media(max-width:599px){.page{height:var(--mobile-height,100dvh);transform:scale(var(--mobile-scale,1));transform-origin:top left}}
</style>
